## 作业

[链接](https://www.kesci.com/home/project/59f29f67c5f3f5119527a2cc)

In [1]:
# 1
import numpy as np

In [2]:
# 2 打印numpy的版本和配置说明
# np.__version__
# np.__config__
np.show_config 

<function numpy.__config__.show()>

In [3]:
# 3.创建一个长度为10的空向量
vector3 = np.zeros(10)
print (vector3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# 4.real.如何找到一个数组的内存大小
print("%d b" %(np.ones(10).size * np.ones(10).itemsize))

80 b


In [5]:
# 5.如何从命令行得到numpy中add函数的说明文档
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [6]:
# 6. 创建一个长度为10并且除了第五个值为1的空向量
a =np.zeros(10)
print(a)
a[4] = 1
a

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [7]:
# 7. 创建一个值域范围从10到49的向量
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
# 8. 反转一个向量(第一个元素变为最后一个) 
x = np.arange(10)
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [9]:
# 9. 创建一个 3x3 并且值从0到8的矩阵
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# 10.找到数组[1,2,0,0,4,0]中非0元素的位置索引
array = np.array([1,2,0,0,4,0])
# np.nonzero(array)
np.where(array != 0)

(array([0, 1, 4], dtype=int64),)

In [11]:
# 11. 创建一个 3x3 的单位矩阵

In [12]:
# 12. 创建一个 3x3x3的随机数组 

In [13]:
# 13. 创建一个 10x10 的随机数组并找到它的最大值和最小值

In [14]:
# 14. 创建一个长度为30的随机向量并找到它的平均值

In [15]:
# 15. 创建一个二维数组，其中边界值为1，其余值为0

In [16]:
# 16. 对于一个存在在数组，如何添加一个用0填充的边界? 
a = np.ones((5, 5))
np.pad(a, pad_width=1, mode='constant', constant_values=0)
# np.info(np.pad)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [17]:
# 17. 以下表达式运行的结果分别是什么?
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

print(0 * np.nan,
      np.nan == np.nan,
      np.inf > np.nan,
      np.nan - np.nan,
      0.3 == 3 * 0.1
)

nan False False nan False


In [18]:
# 18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置
# np.info(np.diag) # 提取对角线或构造对角线数组。
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [19]:
# 19. 创建一个8x8 的矩阵，并且设置成棋盘样式
a = np.zeros((8, 8))
a

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
# 20. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?
np.unravel_index(100,(6,7,8))

(1, 5, 4)

In [22]:
# 21. 用tile函数去创建一个 8x8的棋盘样式矩阵
np.tile(np.array([[0,1],[1,0]]),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [23]:
# 22. 对一个5x5的随机矩阵做归一化
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.63589171 0.78337397 0.58818181 0.21192509 0.58610301]
 [0.76526735 0.91971869 0.6264802  0.07366394 0.        ]
 [0.33932125 0.33040744 0.62196822 0.1700281  0.98063524]
 [0.71738361 0.91891306 0.40415481 0.85776726 0.75875544]
 [0.73090338 0.95667287 1.         0.58685576 0.74322397]]


In [24]:
# 23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？
np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [25]:
# 24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？ 
np.dot(np.ones((5,3)), np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [27]:
# 25. 给定一个一维数组，对其在3到8之间的所有元素取反 
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [30]:
# 26. 下面脚本运行后的结果是什么?
# print(sum(range(5),-1))
# from numpy import *
# print(sum(range(5),-1))

print(sum(range(5),-1))
print(sum(range(5),-1))

10
10


In [32]:
# 27. 考虑一个整数向量Z,下列表达合法的是哪个?
# Z**Z
# 2 << Z >> 2
# Z <- Z
# 1j*Z
# Z/1/1
# Z<Z>Z

Z = np.arange(5)
Z ** Z  

array([  1,   1,   4,  27, 256], dtype=int32)

In [34]:
Z = np.arange(5)
2 << Z >> 2  # false

array([0, 1, 2, 4, 8], dtype=int32)

In [35]:
Z = np.arange(5)
Z <- Z   

array([False, False, False, False, False])

In [38]:
Z = np.arange(5)
1j*Z   

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [40]:
Z = np.arange(5)
# Z<Z>Z    # false

In [42]:
# 28. 下列表达式的结果分别是什么?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

print(np.array(0) / np.array(0)
)
print(np.array(0) // np.array(0)
)
print(np.array([np.nan]).astype(int).astype(float)
)

nan
0
[-2.14748365e+09]


C:\Users\jonxia\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
C:\Users\jonxia\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\jonxia\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in true_divide
  
C:\Users\jonxia\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in floor_divide
  


In [43]:
# # 29. 如何从零位对浮点数组做舍入 ? 
Z = np.random.uniform(-10,+10,10)
# print (np.copysign(np.ceil(np.abs(Z)), Z))

[ -8.   1.   1.   3.  -1. -10.  -9.  -2.   9.   2.]


In [44]:
# 30. 如何找到两个数组中的共同元素?
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 2 3 7]


In [46]:
# 31. 如何忽略所有的 numpy 警告(尽管不建议这么做)?
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

In [47]:
# 32. 下面的表达式是正确的吗? 
# np.sqrt(-1) == np.emath.sqrt(-1)

In [48]:
# 33. 如何得到昨天，今天，明天的日期?
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-08-07
Today is 2019-08-08
Tomorrow is 2019-08-09


In [50]:
# 34. 如何得到所有与2016年7月对应的日期
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [54]:
# 35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)?
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
# np.add(A,B,obj=ut=B)
# np.divide(A,2,out=A)
# np.negative(A,out=A)
# np.multiply(A,B,out=A)

In [56]:
# 36. 用五种不同的方法去提取一个随机数组的整数部分
Z = np.random.uniform(0,10,10)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[6. 8. 3. 1. 2. 0. 1. 1. 2. 8.]
[6. 8. 3. 1. 2. 0. 1. 1. 2. 8.]
[6. 8. 3. 1. 2. 0. 1. 1. 2. 8.]
[6 8 3 1 2 0 1 1 2 8]
[6. 8. 3. 1. 2. 0. 1. 1. 2. 8.]


In [57]:
# 37. 创建一个5x5的矩阵，其中每行的数值范围从0到4
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [59]:
# 38. 通过考虑一个可生成10个整数的函数，来构建一个数组
def generate():
    for x in range(10):
        yield x
np.fromiter(generate(),dtype=float,count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [60]:
# 39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [62]:
# 40. 创建一个长度为10的随机向量，并将其排序
Z = np.random.random(10)
Z.sort()
print(Z)

[0.05583043 0.13564928 0.13729746 0.28145152 0.35224877 0.37485248
 0.67339872 0.78120796 0.83647915 0.92473846]


In [63]:
# 41.对于一个小数组，如何用比 np.sum更快的方式对其求和？
Z = np.arange(10)
np.add.reduce(Z)

45

In [65]:
# 42. 对于两个随机数组A和B，检查它们是否相等
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)
# 方法2
equal = np.array_equal(A,B)
print(equal)

False
False


In [66]:
# 43. 创建一个只读数组(read-only) 
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [67]:
# 44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[0.67091851 1.16765047 1.05849056 0.634678   0.70643569 1.03337903
 0.71042393 0.85056472 0.31577062 1.11456264]
[1.50228314 0.97512847 0.88827863 0.52343812 0.2132563  0.86591697
 0.91068472 1.39410732 1.38333065 0.80803311]


In [69]:
# 45. 创建一个长度为10的向量，并将向量中最大值替换为1
Z = np.random.random(10)
Z[Z.argmax()] = 0
print (Z)

[0.03028924 0.49617518 0.43051781 0.13252855 0.8276025  0.89093745
 0.         0.68317675 0.7367143  0.02852512]


In [71]:
# 46. 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [72]:
# 47. 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [73]:
# 48. 打印每个numpy标量类型的最小值和最大值？
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [74]:
# 49. 如何打印一个数组中的所有数值?
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [75]:
# 50. 给定标量时，如何找到数组中最接近标量的值？
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

34
