In [13]:
import numpy as np
data1 = np.array([1,2,3])
data1

array([1, 2, 3])

In [14]:
data1.shape
data1.dtype

dtype('int32')

## 作业

[链接](https://www.kesci.com/home/project/59f29f67c5f3f5119527a2cc)

In [4]:
# 1
import numpy as np

In [24]:
# 2 打印numpy的版本和配置说明
# np.__version__
# np.__config__
np.show_config 

<function numpy.__config__.show()>

In [31]:
# 3.创建一个长度为10的空向量
vector3 = np.zeros(10)
print (vector3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [32]:
# 4.real.如何找到一个数组的内存大小

# Note

## 4.1Numpy-ndarray

### Creating ndarrays

In [ ]:
# 创建ndarray，n-dimension array
arr1 = np.array([[5,6,7,8,9],[5.0,5.1,5.2,5.3,5.3]])
print(arr1)
# array的维度，一个ndarray必有一个shape（一个表示各维度大小的元组）和一个dtype（一个用于说明数组数据类型的对象）
print( "dim is %s, shape is %s, dtype is %s " %(arr1.ndim, arr1.shape, arr1.dtype))
# 当你在本书中看到“数组”、“NumPy数组”、"ndarray"时，基本上都指的是同一样东西，即ndarray对象。

# 其他创建ndarrays方法，np.zeros，np.ones，np.empty(不安全，有时会返回未初始化的垃圾值)
arr_zeros = np.zeros((3,3,2)) # 3,3,2 3个3行2列的array
np.zeros(1, dtype=np.int8)
# 创建Array的方法如下图

![](https://i.loli.net/2019/08/06/F5uJa1GP6Ux8C7m.jpg)

![](https://i.loli.net/2019/08/06/Nn18S6v9ZlcEQsa.jpg)

### Data Types for ndarrays

![](https://i.loli.net/2019/08/06/b2K5AulTRWUz3qi.jpg)
![](https://i.loli.net/2019/08/06/mcIDWaHYyKfbSlZ.jpg)

In [100]:
# ndarrays的数据类型
# dtype是NumPy灵活交互其它系统的源泉之一，通常只需要知道你所处理的数据的大致类型是浮点数、复数、整数、布尔值、字符串，还是普通的Python对象即可。当你需要控制数据在内存和磁盘中的存储方式时（尤其是对大数据集），那就得了解如何控制存储类型。
arr_dtype = np.array([1.2,3.5])
print(arr_dtype.dtype, arr_dtype)
arr_dtype_float = arr_dtype.astype(np.uint32) # 笔记：调用astype总会创建一个新的数组（一个数据的备份），即使新的dtype与旧的dtype相同。
print(arr_dtype_float.dtype, arr_dtype_float)
# 可以看到经过类型转换小数部分被截掉

float64 [1.2 3.5]
uint32 [1 3]


### Arithmetic with NumPy Arrays

In [106]:
arr_arithmetic = np.array([[1., 2., 3.], [4., 5., 6.]])
arr_arithmetic2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr_arithmetic * arr_arithmetic) # 支持python方式的四则运算
print(arr_arithmetic>=arr_arithmetic2) # 比大小 不同大小的数组之间的运算叫做广播（broadcasting）

[[ 1.  4.  9.]
 [16. 25. 36.]]
[[ True False  True]
 [False  True False]]


### Basic indexing and slicing

In [131]:
arr = np.arange(10)
print(arr)
print(arr[0:8]) # 切片，前闭后开取值
arr[0:1]=1.5 # 会裁掉小数点
print(arr)
# 当将一个标量赋值给一个切片时，该值会自动传播到整个选区。
# 跟列表最重要的区别在于，数组切片是原始数组的视图。这意味着数据不会被复制，视图上的任何修改都会直接反映到源数组上。

arr_slice = arr[5:8]
print(arr_slice)
arr_slice[0] = 12345
print(arr)
arr_slice[:] = 0
print(arr)
# 注意：如果你想要得到的是ndarray切I片的一份副本而非视图，就需要明确地进行复制操作，例如arr[5:8].copy()。

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7]
[1 1 2 3 4 5 6 7 8 9]
[5 6 7]
[    1     1     2     3     4 12345     6     7     8     9]
[1 1 2 3 4 0 0 0 8 9]


#### Indexing with slices - 切片索引

In [160]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d_sli = arr2d[:2,1:] # 取2行，索引1之后的数据
print(arr2d_sli.shape)
print("注意维度",arr2d[2].shape, arr2d[2,:].shape, arr2d[2:,:].shape) # 不同切法维度不一样

(2, 2)
注意维度 (3,) (3,) (1, 3)


### Boolean Indexing

In [174]:
# 还有这种操作？
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

## 神奇的来了
cond = names == 'Bob' # 根据条件形成布尔索引的ndarray对象
print(cond)
print(data[~cond, 2:])
print("\n")
mask = (names == 'Bob') | (names == 'Will') # 来个稍微复杂的
print(data[mask])

[ True False False  True False False False]
[[ 0.98800913 -0.86595461]
 [ 0.65033158  0.50023587]
 [-0.05007125 -1.58476113]
 [-0.6514854   0.17825125]
 [ 1.29464824 -1.20621152]]


[[-2.49374548  0.03890557  0.6791203  -0.36592296]
 [-0.78708169 -0.69738032  0.65033158  0.50023587]
 [-0.54428751  0.01238826 -2.47177124 -0.39092149]
 [ 1.49113396  0.64832223 -0.05007125 -1.58476113]]


### Fancy Indexing - 花式索引

花式索引（Fancy indexing）是一个NumPy术语，它指的是利用整数数组进行索引。

In [188]:
arr = np.arange(32).reshape((8, 4))
arr[[-1,5,7,2],[0,3,1,2]] # 利用数组做索引取值
# 无论数组是多少维的，花式索引总是一维的。

array([28, 23, 29, 10])

In [191]:
# 这个是没看懂的部分
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]
# 记住，花式索引跟切片不一样，它总是将数据复制到新数组中。

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### Transposing Arrays and Swapping Axes

转置是返回的是源数据的视图，不会复制

In [195]:
arr = np.arange(32).reshape(8,4)
arr
arr.T # 求转置矩阵

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [198]:
arr.swapaxes(1,2) 

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

??? 对于高维数组，transpose需要得到一个由轴编号组成的元组才能对这些轴进行转置

In [200]:
arr = np.arange(16).reshape((2, 2, 4))
print(arr)
arr.transpose((1,0,2))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

## 4.2 Universal Functions: Fast Element-Wise Array

In [212]:
arr = np.arange(10)
# 一元通用函数(unary ufunc)
print(np.sqrt(arr))
print(np.exp2(arr))
print("\n")
# 二元通用函数(binary ufunc)
x = np.random.randn(8)
y = np.random.randn(8)
print(x,"\n", y)
print(np.maximum(x, y)) # 求最大元素
print(np.modf(x)) # 求浮点数的ndarray的整数和小数部分

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]


[ 0.80555581 -0.57377696  2.35461918  0.36713285  0.03565297 -1.92216886
 -0.53663091  0.93477407] 
 [-0.49801934 -0.02335047 -1.55624425  0.19719255  0.77285658  0.52273112
 -0.08411199  1.60011814]
[ 0.80555581 -0.02335047  2.35461918  0.36713285  0.77285658  0.52273112
 -0.08411199  1.60011814]
(array([ 0.80555581, -0.57377696,  0.35461918,  0.36713285,  0.03565297,
       -0.92216886, -0.53663091,  0.93477407]), array([ 0., -0.,  2.,  0.,  0., -1., -0.,  0.]))


![](https://i.loli.net/2019/08/06/mHvg87Izl2KDAFM.jpg)
![](https://i.loli.net/2019/08/06/zG3xu17bIo4jelK.jpg)
![](https://i.loli.net/2019/08/06/FP3LeXN5EySr9ni.jpg)

## 4.3 Array-Oriented Programming with Arrays